<?php declare(strict_types=1);
return array(
    array(
        'GET',
        '/',
        'App\Page\Controller#home'
    ),
    array(
        'GET',
        '/home',
        'App\Page\Controller#home'
    ),
    array(
        'GET',
        '/logout',
        'App\Page\Controller#logout'
    ),
    array(
        'GET',
        '/create_user',
        'App\Page\Controller#edit_user'
    ),
    array(
        'GET',
        '/edit_user/{id}',
        'App\Page\Controller#edit_user'
    ),
    array(
        'GET',
        '/delete_user/{id}',
        'App\Page\Controller#delete_user'
    ),
    array(
        'POST',
        '/save_user',
        'App\Page\Controller#save_user'
    ),
    array(
        'GET',
        '/api/{login}/{password}',
        'App\Page\Controller#api'
    ),
    array(
        'POST',
        '/api/{login}/{password}',
        'App\Page\Controller#api'
    ),
);
